expected_ex1 = [{'name': 'Chelsea Livingston', 'residence': '291 Samantha Stream\nEdwardmouth, ME 82256', 'blood_group': 'B+', 'sex': 'F', 'birthdate': '2000-08-17', 'mail': 'dfrancis@yahoo.com'},
       {'name': 'David Davenport', 'residence': '770 Levy Flats\nCunninghamborough, NV 68276',
           'blood_group': 'A+', 'sex': 'M', 'birthdate': '1985-08-11', 'mail': 'mark80@hotmail.com'},
       {'name': 'Shannon Clark', 'residence': '4537 Greene Junctions Suite 448\nNorth Michellefort, IA 09212',
           'blood_group': 'B-', 'sex': 'F', 'birthdate': '1995-03-12', 'mail': 'robertsgina@hotmail.com'},
       {'name': 'Kurt Wiggins', 'residence': '0193 Michelle Points\nRobertsonhaven, GA 44372',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '2000-11-07', 'mail': 'mlittle@hotmail.com'},
       {'name': 'Melissa Jennings', 'residence': '544 Rogers Street Apt. 005\nFoxhaven, ID 27568',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1986-02-04', 'mail': 'shawnpatton@yahoo.com'},
       {'name': 'Sara Williams', 'residence': '67467 Harris Trail Apt. 296\nAlvaradohaven, OH 58498',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1989-01-19', 'mail': 'fbaker@hotmail.com'},
       {'name': 'Tammy Stewart', 'residence': '537 Chelsea Court Apt. 173\nNorth Sandra, MN 44763',
        'blood_group': 'B-', 'sex': 'F', 'birthdate': '2000-09-16', 'mail': 'ehayes@hotmail.com'},
       {'name': 'Eduardo Williams', 'residence': '3000 Megan Wall Suite 719\nSouth Elizabeth, NE 09201',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '1989-10-20', 'mail': 'rileysteve@hotmail.com'},
       {'name': 'John Norman', 'residence': '26190 Hernandez Garden Apt. 407\nAmberland, UT 20701',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '1995-08-05', 'mail': 'danawilliams@hotmail.com'},
       {'name': 'Nancy Thompson', 'residence': 'USCGC Buckley\nFPO AA 66124',
        'blood_group': 'B-', 'sex': 'F', 'birthdate': '1987-08-23', 'mail': 'svargas@yahoo.com'},
       {'name': 'Karina Mccarty', 'residence': '5554 Andrew Squares Apt. 085\nMorganfort, NJ 52135',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1994-10-14', 'mail': 'jgutierrez@gmail.com'},
       {'name': 'Kathleen Gray', 'residence': '98598 Hart Row\nNew Michele, IA 85406', 'blood_group': 'A+',
        'sex': 'F', 'birthdate': '1999-07-16', 'mail': 'michaelmitchell@hotmail.com'},
       {'name': 'Andrew Carter', 'residence': '4446 Peter Orchard\nWhiteland, WA 02828',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '1987-02-13', 'mail': 'amberwilliams@gmail.com'},
       {'name': 'Reginald Williams', 'residence': '990 Martinez Locks\nEast Kevinchester, AR 19201',
        'blood_group': 'AB+', 'sex': 'M', 'birthdate': '1986-05-24', 'mail': 'victoria48@hotmail.com'},
       {'name': 'Raymond Johnson', 'residence': 'Unit 9652 Box 9197\nDPO AE 37867', 'blood_group': 'A+',
        'sex': 'M', 'birthdate': '1992-10-22', 'mail': 'stanleynathaniel@hotmail.com'},
       {'name': 'Denise Harrington', 'residence': 'Unit 7426 Box 4670\nDPO AA 52594',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1991-04-10', 'mail': 'steven96@hotmail.com'},
       {'name': 'Tiffany Mason', 'residence': '99736 Julie Manor\nLynnbury, NV 84436',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1988-10-06', 'mail': 'barbarasmith@hotmail.com'},
       {'name': 'Elizabeth Smith', 'residence': 'USCGC Ray\nFPO AA 76740', 'blood_group': 'A-',
        'sex': 'F', 'birthdate': '1985-11-16', 'mail': 'jasonweiss@hotmail.com'},
       {'name': 'Roy Anderson', 'residence': '49046 Knapp Station Suite 881\nPort Melissamouth, NE 39920',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '2000-08-21', 'mail': 'monica58@hotmail.com'},
       {'name': 'Sean Chambers', 'residence': '897 Patrick Extensions Apt. 820\nSmithton, IL 89455',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '1988-08-14', 'mail': 'gvillanueva@gmail.com'},
       {'name': 'Timothy Vasquez', 'residence': '36380 Smith Creek\nJonestown, ND 57221',
        'blood_group': 'A-', 'sex': 'M', 'birthdate': '1991-12-31', 'mail': 'erica89@hotmail.com'},
       {'name': 'Ronald Fields', 'residence': '1664 Molly Mountains Suite 786\nEast Erik, LA 83783',
        'blood_group': 'A-', 'sex': 'M', 'birthdate': '1994-09-10', 'mail': 'zjackson@yahoo.com'},
       {'name': 'Marc Zamora', 'residence': '644 Michael Trail Suite 068\nMcmillanchester, MO 50373',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '1993-02-22', 'mail': 'drivera@gmail.com'},
       {'name': 'Chad Martinez', 'residence': '762 Pratt Shores\nLake Susanhaven, TX 76312',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '1988-03-19', 'mail': 'andersonjohn@hotmail.com'},
       {'name': 'Annette Blair', 'residence': '047 Gonzalez Valleys\nLake Angelaberg, MI 51646',
        'blood_group': 'B+', 'sex': 'F', 'birthdate': '1993-10-07', 'mail': 'jeffrey18@yahoo.com'},
       {'name': 'Jessica Aguilar', 'residence': '95450 Salas Inlet\nWest Marymouth, WA 88274',
        'blood_group': 'O-', 'sex': 'F', 'birthdate': '1997-04-13', 'mail': 'istone@yahoo.com'},
       {'name': 'Terri Collins', 'residence': '96634 Brandy Hills Suite 248\nEast Dwayne, MT 53005',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1992-11-01', 'mail': 'lisa05@gmail.com'},
       {'name': 'Steven Reed', 'residence': '708 Bass Valleys Apt. 505\nNicoleville, KS 91572',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1995-12-07', 'mail': 'jonathanortega@gmail.com'},
       {'name': 'Travis Coleman', 'residence': 'USNV Anderson\nFPO AP 21595', 'blood_group': 'A+',
        'sex': 'M', 'birthdate': '1993-04-26', 'mail': 'brownglenn@gmail.com'},
       {'name': 'Monica Allen', 'residence': '96816 Bailey Heights Apt. 097\nBullockland, MA 32392',
        'blood_group': 'O-', 'sex': 'F', 'birthdate': '1994-09-23', 'mail': 'thomas52@gmail.com'},
       {'name': 'Edwin Allen', 'residence': '1821 Michael Wells\nDavidside, NV 37948',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1998-10-30', 'mail': 'rachelguzman@hotmail.com'},
       {'name': 'Jared Watkins', 'residence': 'USS Howard\nFPO AE 72864', 'blood_group': 'AB-',
        'sex': 'M', 'birthdate': '1997-08-13', 'mail': 'ybuck@yahoo.com'},
       {'name': 'Lisa Yoder', 'residence': '60212 Jermaine Groves\nKelleyton, SD 68383',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '2000-01-26', 'mail': 'gbrown@gmail.com'},
       {'name': 'Jeffrey Murphy', 'residence': '7855 Rios Mount\nDavidton, SD 14665',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1997-04-24', 'mail': 'samanthacook@hotmail.com'},
       {'name': 'Sandra Beasley', 'residence': '85662 Obrien Mountains Apt. 075\nLake Holly, MT 08110',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1985-10-06', 'mail': 'jasoncharles@hotmail.com'},
       {'name': 'Patricia Garcia', 'residence': '76753 Curtis Mountains\nNew Warren, NJ 27140',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1984-11-30', 'mail': 'vblack@hotmail.com'},
       {'name': 'Jose Serrano', 'residence': '363 Lisa Stream Apt. 453\nNew Bryan, WY 50406',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1991-05-30', 'mail': 'yle@hotmail.com'},
       {'name': 'Michael Mckee', 'residence': '625 Benjamin Walks Suite 873\nNew Brandon, OH 15159',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1996-12-10', 'mail': 'janet61@hotmail.com'},
       {'name': 'William Martin', 'residence': '3039 Perez Fork Apt. 673\nPort Sarastad, RI 30696',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1996-09-13', 'mail': 'williamjohnson@hotmail.com'},
       {'name': 'Cassandra Gonzalez', 'residence': '952 Dickerson Cape Suite 940\nAmymouth, MS 47384',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1992-12-11', 'mail': 'carlsonmitchell@gmail.com'},
       {'name': 'Herbert Mendez', 'residence': '91126 Smith Meadow Apt. 568\nWest Ashleyborough, WI 39020',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1991-10-26', 'mail': 'qgeorge@gmail.com'},
       {'name': 'Catherine Blevins', 'residence': '104 Gray Common Apt. 639\nAyersville, NJ 14608',
        'blood_group': 'O-', 'sex': 'F', 'birthdate': '1984-11-16', 'mail': 'danny95@gmail.com'},
       {'name': 'Alexander Brady', 'residence': '4035 Evans Throughway\nDodsonview, IN 64131',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1996-02-29', 'mail': 'pcraig@hotmail.com'},
       {'name': 'Roger Jackson', 'residence': '748 Keith Prairie\nCollinsside, MO 12951',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1995-05-20', 'mail': 'jenny19@hotmail.com'},
       {'name': 'Brian Ray', 'residence': '1484 Cook Road Apt. 064\nTinamouth, NV 48731',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '1988-10-05', 'mail': 'roger50@gmail.com'},
       {'name': 'Caitlin Werner', 'residence': '070 Brown Tunnel Apt. 448\nBrandonside, IA 13738',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1991-08-06', 'mail': 'jason88@hotmail.com'},
       {'name': 'April Garrett', 'residence': '626 Blackwell Plains Suite 417\nTaylorberg, CO 90315',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1986-02-03', 'mail': 'wwalker@yahoo.com'},
       {'name': 'Virginia Mccoy', 'residence': '86468 Debbie Fields Suite 710\nLopezside, IN 12367',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1989-03-23', 'mail': 'wjones@yahoo.com'},
       {'name': 'Anthony Vincent', 'residence': '08280 Brandon Vista\nEmilyview, WA 27942',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '2000-04-30', 'mail': 'mbrown@yahoo.com'},
       {'name': 'Amanda Jones', 'residence': '38077 Landry Creek\nNorth Gregoryhaven, MT 70158',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1998-08-18', 'mail': 'hmoss@yahoo.com'},
       {'name': 'Alexandra Fisher', 'residence': '982 Patrick Plains\nOrtizchester, KS 82744',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1996-09-02', 'mail': 'erikdavis@yahoo.com'},
       {'name': 'Joseph Johnson', 'residence': '57433 Riggs Neck Apt. 665\nWest Brenda, LA 81992',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1998-02-18', 'mail': 'claudia66@gmail.com'},
       {'name': 'Mark Bailey', 'residence': '41781 Hernandez Glen Suite 827\nLake Dianeview, DC 74040',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1986-08-11', 'mail': 'sarah48@hotmail.com'},
       {'name': 'Lauren Price', 'residence': '43751 Robert Ramp Apt. 167\nSouth Cassandra, DE 10301',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1987-08-10', 'mail': 'sherrygarza@yahoo.com'},
       {'name': 'Antonio Thompson', 'residence': '01052 John Spur Suite 853\nWest Kellyside, AZ 46635',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1988-05-09', 'mail': 'johnmurphy@yahoo.com'},
       {'name': 'Kevin Gilbert', 'residence': '2046 Collins Well\nDanielside, SD 71402',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1997-11-13', 'mail': 'jordanchristine@hotmail.com'},
       {'name': 'Anthony Chambers', 'residence': '35779 Robert Falls\nJohnsonshire, MS 80417',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '2000-02-06', 'mail': 'landrykimberly@yahoo.com'},
       {'name': 'Russell Ward', 'residence': '89609 Erin Glen\nLake Daniel, MI 81451',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1989-03-17', 'mail': 'laura73@yahoo.com'},
       {'name': 'Andrea Jenkins', 'residence': '774 Erin Shore\nNorth Terristad, MO 33719',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '2000-05-11', 'mail': 'amy23@hotmail.com'},
       {'name': 'Scott Anderson', 'residence': '9376 Johnson Prairie\nWatkinsstad, AL 56070',
        'blood_group': 'AB+', 'sex': 'M', 'birthdate': '1999-03-19', 'mail': 'anataylor@yahoo.com'},
       {'name': 'Zachary Parker', 'residence': '5450 Booker Walks Apt. 922\nNew Kristabury, HI 72299',
        'blood_group': 'B+', 'sex': 'M', 'birthdate': '1987-03-31', 'mail': 'johnmarshall@gmail.com'},
       {'name': 'Ryan Howell', 'residence': '766 Brian Coves Apt. 914\nEast Ericfurt, NH 10279',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1997-02-20', 'mail': 'uroberts@gmail.com'},
       {'name': 'William Burns', 'residence': '663 Lori Dam Suite 974\nEllistown, CO 14200',
        'blood_group': 'A+', 'sex': 'M', 'birthdate': '2000-09-18', 'mail': 'rsanders@yahoo.com'},
       {'name': 'Angela Floyd', 'residence': '3197 Jonathan Summit\nLeonstad, CT 84614',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1993-11-29', 'mail': 'sara26@yahoo.com'},
       {'name': 'Brittany Miles', 'residence': '381 Reese Lakes Suite 915\nLoriport, IA 54494',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1992-04-14', 'mail': 'jasonconrad@hotmail.com'},
       {'name': 'Tiffany Morris', 'residence': '51878 Davila Crossing Apt. 508\nDiazport, AL 53519',
        'blood_group': 'O-', 'sex': 'F', 'birthdate': '1998-03-03', 'mail': 'smccall@hotmail.com'},
       {'name': 'Joseph Castaneda', 'residence': '24030 Samantha Meadow\nCarrton, WA 47720',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1985-10-28', 'mail': 'xhall@hotmail.com'},
       {'name': 'Brandi Griffith', 'residence': '51591 Brown Canyon Apt. 899\nSouth Johnport, NV 55691',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1987-12-05', 'mail': 'choikayla@gmail.com'},
       {'name': 'Jamie Henry', 'residence': '177 Reyes Turnpike\nDavidmouth, FL 39705',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1986-04-25', 'mail': 'richardwilson@hotmail.com'},
       {'name': 'Beth Webb', 'residence': '2112 Anderson Pine\nMichellestad, MD 78518',
        'blood_group': 'O-', 'sex': 'F', 'birthdate': '1999-07-27', 'mail': 'aprilmartin@yahoo.com'},
       {'name': 'Dr. Kathleen Perkins DDS', 'residence': '42164 Byrd Meadows\nPatriciafort, SC 14593',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1987-12-25', 'mail': 'emcneil@yahoo.com'},
       {'name': 'John Gutierrez', 'residence': '6592 Leslie Mission Apt. 030\nWest Tannerburgh, IL 23340',
        'blood_group': 'A-', 'sex': 'M', 'birthdate': '1989-12-15', 'mail': 'ogonzalez@yahoo.com'},
       {'name': 'Michelle Day DDS', 'residence': '16982 Roman Ford\nNew Jack, NH 01915',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1986-09-16', 'mail': 'ryan46@gmail.com'},
       {'name': 'Debbie Johnson', 'residence': '0741 Harvey Garden Apt. 712\nSouth Karenburgh, SC 66876',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1993-10-23', 'mail': 'qbean@yahoo.com'},
       {'name': 'Shawn Romero', 'residence': '476 Andrew Mission Apt. 784\nPort Emilyport, WV 70973',
        'blood_group': 'AB+', 'sex': 'M', 'birthdate': '1996-04-15', 'mail': 'morganjones@yahoo.com'},
       {'name': 'Tyler Jacobson', 'residence': '71967 Raymond Freeway Apt. 381\nLake Daniel, NC 32522',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1990-09-08', 'mail': 'andreaedwards@gmail.com'},
       {'name': 'Joseph Duncan', 'residence': 'USS Martinez\nFPO AP 57190', 'blood_group': 'A-',
        'sex': 'M', 'birthdate': '1989-04-03', 'mail': 'ginasingleton@gmail.com'},
       {'name': 'Matthew Cook', 'residence': '20759 Scott Summit Suite 766\nLake Williamton, FL 95424',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1988-10-08', 'mail': 'qhamilton@yahoo.com'},
       {'name': 'Anita Garcia', 'residence': '424 Williams Unions\nKathleenville, SC 99632',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1985-11-17', 'mail': 'wmurillo@hotmail.com'},
       {'name': 'Angela Webb', 'residence': '00838 Walsh Union\nDanielhaven, WI 57872',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1993-10-18', 'mail': 'ithomas@hotmail.com'},
       {'name': 'Emily Evans', 'residence': '226 Bruce Lake Suite 140\nGeorgeport, TX 59855',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1985-08-28', 'mail': 'sara25@yahoo.com'},
       {'name': 'David Bell', 'residence': '85269 Espinoza Villages\nMathewfort, PA 26879',
        'blood_group': 'A+', 'sex': 'M', 'birthdate': '1996-06-25', 'mail': 'russelltaylor@yahoo.com'},
       {'name': 'Henry Lewis', 'residence': 'Unit 3116 Box 7009\nDPO AE 95824', 'blood_group': 'AB-',
        'sex': 'M', 'birthdate': '1991-03-31', 'mail': 'keithrivera@gmail.com'},
       {'name': 'Bailey Sanders', 'residence': '7472 Steven Landing\nMortontown, CO 99075',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1992-10-22', 'mail': 'gary16@hotmail.com'},
       {'name': 'Emily Adams', 'residence': '56889 Benjamin Cape Apt. 165\nNorth Shelly, NM 91367',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1993-02-10', 'mail': 'wheelerrobert@hotmail.com'},
       {'name': 'Emily Porter', 'residence': '2899 Kelley Creek\nSouth Cindyhaven, PA 21262',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1987-05-25', 'mail': 'danielsmith@hotmail.com'},
       {'name': 'Michael Hudson', 'residence': '4606 Walker Flats Suite 286\nGraymouth, KS 75870',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1998-03-12', 'mail': 'kristina11@yahoo.com'},
       {'name': 'Eric Vazquez', 'residence': '7122 Brandt Turnpike\nFritzview, SD 15206',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1986-11-18', 'mail': 'qrobinson@hotmail.com'},
       {'name': 'Jessica Richardson', 'residence': '501 Briana Circle Suite 830\nCrawfordfurt, WV 46474',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1988-03-19', 'mail': 'jonesmeghan@hotmail.com'},
       {'name': 'Scott Boyd', 'residence': '43947 Andrew Lake Apt. 991\nJillside, SC 60267',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1997-07-11', 'mail': 'gdavis@gmail.com'},
       {'name': 'Ashley Gibbs', 'residence': '3083 Gregory Road\nBryantberg, HI 73949',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1997-10-16', 'mail': 'tuckeradam@hotmail.com'},
       {'name': 'Natalie Davenport', 'residence': '500 Jennifer Bypass\nWest Christina, IA 74917',
        'blood_group': 'B-', 'sex': 'F', 'birthdate': '1987-09-11', 'mail': 'kcarroll@gmail.com'},
       {'name': 'Scott Lee', 'residence': '92471 Howell Field\nHoodchester, WA 45357',
        'blood_group': 'O+', 'sex': 'M', 'birthdate': '1997-01-14', 'mail': 'dmoore@yahoo.com'},
       {'name': 'Rodney Davis', 'residence': '9768 Jenna Road Suite 923\nLisaton, ID 64383',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '1996-05-23', 'mail': 'bryan46@hotmail.com'},
       {'name': 'Amy Barnes', 'residence': '0169 Murphy Light\nNorth Anthonyfort, KS 01289',
        'blood_group': 'B-', 'sex': 'F', 'birthdate': '1987-05-19', 'mail': 'ipowers@gmail.com'},
       {'name': 'Emily Bernard', 'residence': '39446 Jordan Walks Suite 254\nSouth Amyton, NJ 74961',
        'blood_group': 'B+', 'sex': 'F', 'birthdate': '1993-10-11', 'mail': 'moorejames@yahoo.com'},
       {'name': 'Steven Espinoza', 'residence': '5422 David Station\nLydiatown, NC 65818',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1988-04-23', 'mail': 'fmartinez@gmail.com'},
       {'name': 'Laura Mitchell', 'residence': '846 Maldonado Loaf Apt. 288\nPort Benjaminview, AZ 67724',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1997-10-17', 'mail': 'ilynch@hotmail.com'},
       {'name': 'Aaron Martinez', 'residence': '332 Ruth Cove\nSantiagomouth, AR 67410',
        'blood_group': 'A+', 'sex': 'M', 'birthdate': '1990-11-01', 'mail': 'christianthomas@hotmail.com'},
       {'name': 'Angela Blankenship', 'residence': '3383 Janet Fords\nProctormouth, OK 33099',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1992-05-20', 'mail': 'figueroachristine@gmail.com'},
       {'name': 'Jennifer Whitney', 'residence': '9032 Boone Courts\nLaurenborough, RI 16627',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1987-01-11', 'mail': 'omcdonald@gmail.com'},
       {'name': 'Jorge Martinez', 'residence': '98099 Parks Cove\nAndrewsborough, VT 17071',
        'blood_group': 'A+', 'sex': 'M', 'birthdate': '1989-03-06', 'mail': 'hbush@gmail.com'},
       {'name': 'Madeline Bryant', 'residence': 'PSC 4691, Box 1636\nAPO AA 14292', 'blood_group': 'O-',
        'sex': 'F', 'birthdate': '1992-04-01', 'mail': 'wilsonnicole@hotmail.com'},
       {'name': 'Linda Mcbride', 'residence': '3045 Palmer Expressway\nEmilyton, RI 20054',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1995-09-18', 'mail': 'lbrady@hotmail.com'},
       {'name': 'Shari Hardy', 'residence': '35476 Grimes Lane\nNorth Dawn, CA 98968',
        'blood_group': 'B+', 'sex': 'F', 'birthdate': '1989-03-11', 'mail': 'tsparks@hotmail.com'},
       {'name': 'Linda Prince', 'residence': '325 Christina Fords Apt. 750\nEast Lisaburgh, MI 39006',
        'blood_group': 'A-', 'sex': 'F', 'birthdate': '1993-11-04', 'mail': 'alierin@yahoo.com'},
       {'name': 'Jill Knight', 'residence': '873 Lewis Pines\nRichardsonborough, SD 45810',
        'blood_group': 'AB-', 'sex': 'F', 'birthdate': '1994-07-13', 'mail': 'fcrane@yahoo.com'},
       {'name': 'Anne Perez', 'residence': '2982 Kristin Orchard\nSouth Jessicaport, MN 20338',
        'blood_group': 'O-', 'sex': 'F', 'birthdate': '1999-09-01', 'mail': 'steven41@hotmail.com'},
       {'name': 'Matthew Avery', 'residence': '814 Tracy Cape\nGarciabury, SC 87824',
        'blood_group': 'A+', 'sex': 'M', 'birthdate': '1994-06-26', 'mail': 'hillkelly@hotmail.com'},
       {'name': 'Paul Barnett', 'residence': '94452 Patricia Crescent Apt. 173\nSethburgh, MS 15884',
        'blood_group': 'AB+', 'sex': 'M', 'birthdate': '1994-12-13', 'mail': 'maxwell80@gmail.com'},
       {'name': 'Angela Lawson', 'residence': '27742 Henderson Mount\nWaltersburgh, DC 58943',
        'blood_group': 'AB+', 'sex': 'F', 'birthdate': '1986-08-16', 'mail': 'bellphilip@hotmail.com'},
       {'name': 'Mr. Stephen Ruiz', 'residence': '3472 White Place\nNew Rebecca, MS 04335',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '1992-03-07', 'mail': 'jkelly@hotmail.com'},
       {'name': 'Christopher Baker', 'residence': '71765 Douglas Harbor\nRubenfurt, IA 47032',
        'blood_group': 'AB-', 'sex': 'M', 'birthdate': '1986-05-04', 'mail': 'maykenneth@gmail.com'},
       {'name': 'Casey Moran', 'residence': '5228 Rivas Centers Suite 916\nLisabury, LA 44664',
        'blood_group': 'B-', 'sex': 'F', 'birthdate': '1985-12-30', 'mail': 'damon24@hotmail.com'},
       {'name': 'Mr. Lee Guzman', 'residence': '994 Williams Views Suite 688\nPort Taylortown, OH 58694',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1995-01-15', 'mail': 'jnewman@hotmail.com'},
       {'name': 'Michael Castillo', 'residence': '7551 Williams Coves\nWrightfurt, ND 68152',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1988-03-15', 'mail': 'xfreeman@hotmail.com'},
       {'name': 'Cynthia Wallace', 'residence': '5628 Laura Light Suite 350\nEast Carlosfort, WA 21257',
        'blood_group': 'B-', 'sex': 'F', 'birthdate': '1986-01-08', 'mail': 'jamespaul@yahoo.com'},
       {'name': 'Gerald Brewer', 'residence': 'PSC 5655, Box 9331\nAPO AP 64396', 'blood_group': 'B+',
        'sex': 'M', 'birthdate': '1992-10-02', 'mail': 'jameschandler@gmail.com'},
       {'name': 'Joseph Barry MD', 'residence': '753 Amanda Branch Suite 516\nSouth Benjaminstad, NC 21047',
        'blood_group': 'A+', 'sex': 'M', 'birthdate': '1987-09-24', 'mail': 'michael52@yahoo.com'},
       {'name': 'Thomas Kane', 'residence': '5422 William Cliffs Apt. 370\nPort Brian, NV 23843',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1998-08-14', 'mail': 'ebecker@hotmail.com'},
       {'name': 'Russell Martinez', 'residence': '680 Kim Row Suite 930\nLewisfurt, AL 43096',
        'blood_group': 'B-', 'sex': 'M', 'birthdate': '1991-11-13', 'mail': 'ian72@yahoo.com'},
       {'name': 'Lauren Jensen', 'residence': '89831 Martinez Burg\nWest Maria, NJ 04622',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1985-10-24', 'mail': 'gerald71@gmail.com'},
       {'name': 'Ricardo Allen', 'residence': '000 Weber Summit Suite 211\nSusanside, AZ 04145',
        'blood_group': 'O-', 'sex': 'M', 'birthdate': '1987-11-18', 'mail': 'perryrachel@yahoo.com'},
       {'name': 'Sarah Burton', 'residence': '79198 Joseph Port\nErintown, CO 89366',
        'blood_group': 'O+', 'sex': 'F', 'birthdate': '1991-01-12', 'mail': 'awebb@gmail.com'},
       {'name': 'Tyler Fuentes', 'residence': '364 Jenkins Manors Apt. 221\nGilbertmouth, NY 37468',
        'blood_group': 'AB+', 'sex': 'M', 'birthdate': '1999-08-28', 'mail': 'hmadden@gmail.com'},
       {'name': 'Megan Williams', 'residence': '9811 Jennifer Drives\nMonicafurt, HI 69889',
        'blood_group': 'A+', 'sex': 'F', 'birthdate': '1985-10-13', 'mail': 'ujohnson@yahoo.com'},
       {'name': 'John Munoz', 'residence': '93889 Michelle Viaduct\nNew Caleb, OK 11493', 'blood_group': 'O+', 'sex': 'M', 'birthdate': '1994-03-15', 'mail': 'yleonard@hotmail.com'}]


expected_ex2 = [{'name': 'Amy Williams', 'mail': 'christian57@yahoo.com', 'residence': 'Unit 6898 Box 6260\nDPO AE 40404'},
       {'name': 'Julia Smith', 'mail': 'lucaskaiser@gmail.com',
           'residence': '1362 Moore Lakes\nOrtizhaven, HI 90443'},
       {'name': 'Christina Turner', 'mail': 'jonathan92@yahoo.com',
           'residence': '06552 Rodriguez Drive Apt. 584\nAliceshire, AZ 70253'},
       {'name': 'Melanie Mccullough', 'mail': 'bakerlauren@gmail.com',
        'residence': '34386 Phillip Way\nNew Thomas, DE 11350'},
       {'name': 'Jeffrey Gray', 'mail': 'timothy22@hotmail.com',
        'residence': '5290 Joseph Row Apt. 198\nNorth Katherine, NE 76746'},
       {'name': 'Manuel English', 'mail': 'ronaldcarter@hotmail.com',
        'residence': '50104 Jones Knolls\nLake Ashleyland, KY 74703'},
       {'name': 'Leslie Young', 'mail': 'janemills@yahoo.com',
        'residence': '994 Ellis Green Apt. 906\nRobinsonshire, WI 63906'},
       {'name': 'Ruben Hernandez', 'mail': 'kaylabriggs@gmail.com',
        'residence': 'PSC 4374, Box 6344\nAPO AA 39922'},
       {'name': 'Sarah Garcia', 'mail': 'steinjason@gmail.com',
        'residence': '66502 Gonzalez Lodge Suite 190\nPort Brian, VA 47637'},
       {'name': 'Anna Brown', 'mail': 'jenkinskatherine@gmail.com',
        'residence': '117 Janice Greens\nMckenzieton, PA 85163'},
       {'name': 'Jessica Johnson', 'mail': 'joshua22@yahoo.com',
        'residence': '57077 Christopher Plaza Suite 019\nAnthonyburgh, CO 07071'},
       {'name': 'Caitlin Perez', 'mail': 'stanleycody@yahoo.com',
        'residence': '17270 Kimberly Unions\nPort Michael, DC 50087'},
       {'name': 'Linda Frazier', 'mail': 'jacksonbetty@gmail.com',
        'residence': '6705 Sean Villages\nHodgeburgh, CA 19366'},
       {'name': 'Mr. David Ortiz', 'mail': 'kdavis@gmail.com',
        'residence': '928 Schmidt Tunnel\nChristinashire, WY 33268'},
       {'name': 'Ricky Lopez', 'mail': 'melissaboyd@gmail.com',
        'residence': '9964 Obrien Stravenue Apt. 242\nYoungfort, WA 34082'},
       {'name': 'Kylie Lee', 'mail': 'nataliebyrd@gmail.com',
        'residence': '39990 Cox View\nEdwardfort, RI 82199'},
       {'name': 'Lori Neal', 'mail': 'marshsandy@gmail.com',
        'residence': '73096 Martinez Drive\nKaylaton, AK 55885'},
       {'name': 'Karina Mccarty', 'mail': 'jgutierrez@gmail.com',
        'residence': '5554 Andrew Squares Apt. 085\nMorganfort, NJ 52135'},
       {'name': 'Paul Palmer', 'mail': 'jamescathy@hotmail.com',
        'residence': 'Unit 6200 Box 7165\nDPO AE 33879'},
       {'name': 'April Perkins', 'mail': 'sjenkins@hotmail.com',
        'residence': '54503 Kayla Station Apt. 257\nNorth Kimberlyfurt, AZ 65847'},
       {'name': 'Joseph Young', 'mail': 'mitchellryan@hotmail.com',
        'residence': '104 Abigail Brooks\nJamesbury, IL 70653'},
       {'name': 'Maria Bryant', 'mail': 'rachelsaunders@hotmail.com',
        'residence': '4718 Graves Lights\nRobertshire, MT 93924'},
       {'name': 'David Cohen', 'mail': 'awalker@hotmail.com',
        'residence': '47203 Leslie Hill Apt. 836\nWest Shawnfort, MA 65068'},
       {'name': 'Matthew Walters', 'mail': 'iallen@gmail.com',
        'residence': '166 Travis Roads\nEast Michael, ND 47766'},
       {'name': 'Scott Robinson DDS', 'mail': 'linda45@hotmail.com',
        'residence': '781 Nixon Mall Suite 217\nValerieberg, KS 86270'},
       {'name': 'Melissa Kennedy', 'mail': 'amanda13@gmail.com',
        'residence': '083 Tyler Falls Suite 820\nJonesburgh, AK 84937'},
       {'name': 'Timothy Vasquez', 'mail': 'erica89@hotmail.com',
        'residence': '36380 Smith Creek\nJonestown, ND 57221'},
       {'name': 'Ronald Fields', 'mail': 'zjackson@yahoo.com',
        'residence': '1664 Molly Mountains Suite 786\nEast Erik, LA 83783'},
       {'name': 'Gerald Massey', 'mail': 'kristenpeters@gmail.com',
        'residence': '23493 Matthews Point Apt. 259\nKleinton, NJ 85201'},
       {'name': 'James Mendoza', 'mail': 'ritacarroll@hotmail.com',
        'residence': '75235 Harvey Bypass\nMarcfort, MO 78585'},
       {'name': 'Tina Kennedy', 'mail': 'john28@gmail.com',
        'residence': '5105 Zachary Tunnel Suite 509\nMichaelton, NE 99744'},
       {'name': 'Robert Nguyen', 'mail': 'samuel50@hotmail.com',
        'residence': '0833 Fry Parkways\nNew Jeffreymouth, ND 98011'},
       {'name': 'Jessica Aguilar', 'mail': 'istone@yahoo.com',
        'residence': '95450 Salas Inlet\nWest Marymouth, WA 88274'},
       {'name': 'Shelby Atkins', 'mail': 'joshua28@gmail.com',
        'residence': '1225 Kirk Ports\nJacquelinechester, CA 71332'},
       {'name': 'Michael Miller', 'mail': 'daniellekrueger@yahoo.com',
        'residence': '823 Lee Unions\nEast Kaylaton, NH 02608'},
       {'name': 'Robert Love', 'mail': 'rebeccapalmer@yahoo.com',
        'residence': '138 Nolan Inlet\nNorth Donald, TN 87940'},
       {'name': 'Chad Smith', 'mail': 'scottbanks@gmail.com',
        'residence': 'USNS May\nFPO AP 48500'},
       {'name': 'Steven Reed', 'mail': 'jonathanortega@gmail.com',
        'residence': '708 Bass Valleys Apt. 505\nNicoleville, KS 91572'},
       {'name': 'Monica Allen', 'mail': 'thomas52@gmail.com',
        'residence': '96816 Bailey Heights Apt. 097\nBullockland, MA 32392'},
       {'name': 'Monique Armstrong', 'mail': 'davidbeard@yahoo.com',
        'residence': 'USCGC Wong\nFPO AP 86812'},
       {'name': 'Edwin Allen', 'mail': 'rachelguzman@hotmail.com',
        'residence': '1821 Michael Wells\nDavidside, NV 37948'},
       {'name': 'Denise Gonzales', 'mail': 'carterwilliam@hotmail.com',
        'residence': '65921 Calhoun Lights Apt. 193\nAustinchester, CA 20144'},
       {'name': 'Catherine Williams MD', 'mail': 'bhorton@gmail.com',
        'residence': '57442 Jones Freeway\nWest Hannah, OH 96343'},
       {'name': 'Nicole English', 'mail': 'howardconnor@gmail.com',
        'residence': 'Unit 6004 Box 8254\nDPO AA 31175'},
       {'name': 'Heather Robinson', 'mail': 'brownmatthew@yahoo.com',
        'residence': 'USNV Taylor\nFPO AE 79052'},
       {'name': 'Sarah Ross', 'mail': 'dgonzalez@yahoo.com',
        'residence': 'PSC 1486, Box 9498\nAPO AA 67022'},
       {'name': 'Ryan Jones', 'mail': 'robertsonjean@hotmail.com',
        'residence': '926 Wendy Burgs\nSouth Georgeborough, NH 84681'},
       {'name': 'Michele Burnett', 'mail': 'kjohnson@gmail.com',
        'residence': '606 Rodriguez Extension\nHillview, KS 74868'},
       {'name': 'Suzanne Woodward', 'mail': 'mark57@yahoo.com',
        'residence': '82294 Smith Lock\nEast Carrie, MI 52006'},
       {'name': 'Robin Mayo', 'mail': 'xfleming@hotmail.com',
        'residence': '2159 Heather Forks\nWest Jose, PA 96387'},
       {'name': 'Herbert Mendez', 'mail': 'qgeorge@gmail.com',
        'residence': '91126 Smith Meadow Apt. 568\nWest Ashleyborough, WI 39020'},
       {'name': 'Catherine Blevins', 'mail': 'danny95@gmail.com',
        'residence': '104 Gray Common Apt. 639\nAyersville, NJ 14608'},
       {'name': 'Mary Crawford', 'mail': 'mejiafrances@yahoo.com',
        'residence': '0596 Harris Lodge Apt. 720\nMccormickside, NH 78114'},
       {'name': 'Jonathan Barton', 'mail': 'jillian40@gmail.com',
        'residence': '7251 Keith Rapid Apt. 607\nEast Steven, WA 79628'},
       {'name': 'Jeffrey Stevenson', 'mail': 'mcclaincarl@yahoo.com',
        'residence': '93986 Nicholas Canyon\nEdwardland, KS 97706'},
       {'name': 'Dennis Webster', 'mail': 'xmartin@gmail.com',
        'residence': '4369 Dominguez Haven Suite 728\nNew Justinchester, AL 07123'},
       {'name': 'Joseph Johnson', 'mail': 'claudia66@gmail.com',
        'residence': '57433 Riggs Neck Apt. 665\nWest Brenda, LA 81992'},
       {'name': 'Isaac Foster', 'mail': 'ashleyboyle@yahoo.com',
        'residence': '862 Lara Ports Apt. 050\nZacharybury, ME 74602'},
       {'name': 'Antonio Roberts', 'mail': 'angelicahansen@hotmail.com',
        'residence': '791 Carmen Meadows Suite 475\nJuarezfort, MN 85186'},
       {'name': 'Holly Gallagher', 'mail': 'jameswest@gmail.com',
        'residence': '646 Brown Courts Apt. 918\nNorth Jack, OH 29713'},
       {'name': 'Morgan Gregory', 'mail': 'bdonovan@hotmail.com',
        'residence': '00669 Audrey Glens Suite 801\nEast David, CT 81140'},
       {'name': 'Kevin Gilbert', 'mail': 'jordanchristine@hotmail.com',
        'residence': '2046 Collins Well\nDanielside, SD 71402'},
       {'name': 'Christopher Williams', 'mail': 'michaelmorgan@gmail.com',
        'residence': '80377 William Path Suite 632\nSmithshire, TN 89237'},
       {'name': 'Bradley Allen', 'mail': 'carl25@yahoo.com',
        'residence': '897 Brandi Grove Suite 952\nLake Tammyville, AL 76949'},
       {'name': 'Diane Hall', 'mail': 'dennismurphy@gmail.com',
        'residence': 'PSC 2107, Box 2996\nAPO AA 08294'},
       {'name': 'Amy Williams', 'mail': 'eatonsamantha@hotmail.com',
        'residence': '560 Haynes Motorway\nJohnsonberg, AZ 85515'},
       {'name': 'Edward Blevins', 'mail': 'pattonstanley@yahoo.com',
        'residence': '27898 Boyd Trace\nPort Cheyennemouth, MN 91800'},
       {'name': 'Theresa Harrison', 'mail': 'mark61@hotmail.com',
        'residence': '42791 Adams Drives Suite 357\nSouth Tracy, IA 17226'},
       {'name': 'Ryan Howell', 'mail': 'uroberts@gmail.com',
        'residence': '766 Brian Coves Apt. 914\nEast Ericfurt, NH 10279'},
       {'name': 'Karen Padilla', 'mail': 'shaney@gmail.com',
        'residence': '16080 Logan Stream Suite 520\nHammondside, NH 75368'},
       {'name': 'Janet Ramsey', 'mail': 'nicolewright@hotmail.com',
        'residence': '78640 Ashley Ports Suite 082\nSouth Jacob, NM 55550'},
       {'name': 'Tiffany Morris', 'mail': 'smccall@hotmail.com',
        'residence': '51878 Davila Crossing Apt. 508\nDiazport, AL 53519'},
       {'name': 'Daniel Alexander', 'mail': 'kelly96@yahoo.com',
        'residence': '709 Gill Lodge\nMarymouth, ID 70149'},
       {'name': 'Erica Anderson', 'mail': 'whitebenjamin@gmail.com',
        'residence': '00408 Melissa Mountain\nNew Dennis, MN 37081'},
       {'name': 'Jack Moon', 'mail': 'butlerdarrell@hotmail.com',
        'residence': '7381 Dana Knolls\nAlexanderton, FL 06024'},
       {'name': 'Beth Webb', 'mail': 'aprilmartin@yahoo.com',
        'residence': '2112 Anderson Pine\nMichellestad, MD 78518'},
       {'name': 'Emily Hurley', 'mail': 'lbrown@hotmail.com',
        'residence': '5030 Shaw Centers Suite 795\nBlakefurt, VA 17839'},
       {'name': 'Karen Martinez', 'mail': 'cynthiagonzalez@yahoo.com',
        'residence': '34907 Laura Light Suite 005\nNorth Danielfurt, AR 88973'},
       {'name': 'John Gutierrez', 'mail': 'ogonzalez@yahoo.com',
        'residence': '6592 Leslie Mission Apt. 030\nWest Tannerburgh, IL 23340'},
       {'name': 'Charles Gonzalez', 'mail': 'daniel74@yahoo.com',
        'residence': '0943 Kelly Burg\nLake Tina, NY 53012'},
       {'name': 'Debbie Johnson', 'mail': 'qbean@yahoo.com',
        'residence': '0741 Harvey Garden Apt. 712\nSouth Karenburgh, SC 66876'},
       {'name': 'Carl Mercer', 'mail': 'margaret35@gmail.com',
        'residence': '564 Sharon Ways\nWest Denisefort, OR 80320'},
       {'name': 'Lori Keller', 'mail': 'wjohnson@gmail.com',
        'residence': '5250 Graves Land Apt. 754\nRobertberg, TX 05344'},
       {'name': 'Michael Bell', 'mail': 'andradejose@gmail.com',
        'residence': '32487 Rangel Springs\nSouth Jilltown, NJ 37460'},
       {'name': 'Jason Mills', 'mail': 'xmaynard@gmail.com',
        'residence': '68178 Obrien Lodge Apt. 541\nSouth Lydia, WA 04638'},
       {'name': 'Tyler Jacobson', 'mail': 'andreaedwards@gmail.com',
        'residence': '71967 Raymond Freeway Apt. 381\nLake Daniel, NC 32522'},
       {'name': 'Kenneth Johnson', 'mail': 'norriskenneth@hotmail.com',
        'residence': '570 Sheila Drive\nLake Lindaborough, NY 73938'},
       {'name': 'Jennifer Wells', 'mail': 'lori01@gmail.com',
        'residence': '99422 Keith Parkway\nNorth Brittany, CA 92230'},
       {'name': 'Megan Marks', 'mail': 'turnerryan@gmail.com',
        'residence': '05480 Douglas Forest\nNorth Sharon, AK 62729'},
       {'name': 'Keith Brennan', 'mail': 'molly28@gmail.com',
        'residence': '80479 Richard Crossing\nGilmoreberg, PA 74816'},
       {'name': 'Joshua Smith', 'mail': 'gomezbrian@hotmail.com',
        'residence': '8335 Walker Courts\nEast Johnmouth, UT 07232'},
       {'name': 'Kathy Pearson', 'mail': 'timothy49@hotmail.com',
        'residence': '44780 Lee Burgs\nPort Pamela, PA 05910'},
       {'name': 'Karen Clarke', 'mail': 'stevenjones@yahoo.com',
        'residence': '570 Singh Fall Apt. 511\nNorth Tanyafurt, HI 83295'},
       {'name': 'Lisa Brown', 'mail': 'smithdouglas@gmail.com',
        'residence': '37227 James Prairie\nSouth Toddtown, MI 24938'},
       {'name': 'Victoria Wagner', 'mail': 'allenjustin@gmail.com',
        'residence': '06245 Hopkins Shores\nLake David, NJ 19017'},
       {'name': 'Ashley Gibbs', 'mail': 'tuckeradam@hotmail.com',
        'residence': '3083 Gregory Road\nBryantberg, HI 73949'},
       {'name': 'Kelli Kennedy', 'mail': 'ztucker@hotmail.com',
        'residence': '98204 Irwin Key Suite 164\nEast Johnburgh, UT 93617'},
       {'name': 'David Clarke', 'mail': 'ayalabrandon@yahoo.com',
        'residence': '131 Ramsey Passage\nManningport, SC 56553'},
       {'name': 'Christine Gonzalez', 'mail': 'ywatson@hotmail.com',
        'residence': '955 Ray Lock Apt. 212\nYvetteview, GA 58282'},
       {'name': 'Brent Duffy', 'mail': 'zchung@yahoo.com',
        'residence': '712 Bonnie Orchard Suite 652\nSouth Taylor, AR 56634'},
       {'name': 'Sarah Bryan', 'mail': 'tyler37@gmail.com',
        'residence': '5479 William Summit Suite 494\nEast Luismouth, MT 03275'},
       {'name': 'Jennifer Cherry', 'mail': 'wvasquez@yahoo.com',
        'residence': '60850 Sutton Shoal Apt. 937\nSouth Matthew, MN 62446'},
       {'name': 'Jamie Martin', 'mail': 'kelly10@yahoo.com',
        'residence': '32432 Michelle Trafficway Apt. 020\nJaredport, KS 72092'},
       {'name': 'Steven Espinoza', 'mail': 'fmartinez@gmail.com',
        'residence': '5422 David Station\nLydiatown, NC 65818'},
       {'name': 'Lynn Jackson', 'mail': 'ilamb@yahoo.com',
        'residence': '461 Pitts Trail Suite 154\nNorth Jesse, OK 60598'},
       {'name': 'Mark James', 'mail': 'vazquezzachary@gmail.com',
        'residence': 'Unit 0402 Box 0120\nDPO AP 14637'},
       {'name': 'Michelle House', 'mail': 'ahardy@hotmail.com',
        'residence': '7015 Maria Unions Suite 206\nJacquelinefurt, NV 80367'},
       {'name': 'Matthew Mccarthy', 'mail': 'savannah64@yahoo.com',
        'residence': '6614 Johnson Keys Apt. 534\nMerrittport, WI 31092'},
       {'name': 'Brittany Jackson', 'mail': 'jacqueline04@hotmail.com',
        'residence': '8337 Alicia Heights Apt. 076\nRiddleshire, SD 00550'},
       {'name': 'Jose Garcia', 'mail': 'paul90@yahoo.com',
        'residence': '868 Franklin Manors\nPort Victoriaburgh, AR 70959'},
       {'name': 'Jeremy Shelton', 'mail': 'grantkimberly@hotmail.com',
        'residence': '760 Brett Tunnel\nHendrickston, IA 94537'},
       {'name': 'Judy Miranda MD', 'mail': 'pdecker@gmail.com',
        'residence': '910 Goodman Shores\nNew Sarabury, WA 22670'},
       {'name': 'Danielle Walker', 'mail': 'peter94@hotmail.com',
        'residence': '8074 Olivia Shoal\nThomasfurt, NM 61782'},
       {'name': 'Lindsey Sellers', 'mail': 'hartwilliam@hotmail.com',
        'residence': '7564 Christine Hill\nAndreamouth, MA 97639'},
       {'name': 'Charles Sosa', 'mail': 'mackjoshua@hotmail.com',
        'residence': '2524 Hoffman Islands\nLake Brian, NV 85395'},
       {'name': 'Lisa Howell', 'mail': 'taylormaria@gmail.com',
        'residence': '52131 Hart Brooks\nThomastown, FL 08560'},
       {'name': 'Madeline Bryant', 'mail': 'wilsonnicole@hotmail.com',
        'residence': 'PSC 4691, Box 1636\nAPO AA 14292'},
       {'name': 'Crystal Orozco', 'mail': 'joel23@gmail.com',
        'residence': '13773 Gibbs Haven\nNorth Cynthia, NY 55116'},
       {'name': 'Shelby Nichols', 'mail': 'christine74@gmail.com',
        'residence': '738 Alison Fords Apt. 720\nBrownfurt, KS 19988'},
       {'name': 'Shelby Vazquez', 'mail': 'ylane@gmail.com',
        'residence': '36363 Alexandra Walk\nPhillipshire, NY 56048'},
       {'name': 'Angela Sanchez', 'mail': 'turnercorey@hotmail.com',
        'residence': '889 Brian Dam Apt. 925\nHurstton, AK 12429'},
       {'name': 'John Pierce', 'mail': 'shawnrivera@gmail.com',
        'residence': '666 Whitehead Drive\nNorth Mackenzie, FL 32648'},
       {'name': 'Linda Prince', 'mail': 'alierin@yahoo.com',
        'residence': '325 Christina Fords Apt. 750\nEast Lisaburgh, MI 39006'},
       {'name': 'Mary Williams', 'mail': 'deanna21@yahoo.com',
        'residence': '255 Vasquez Neck\nPort Kimberlyburgh, IL 87746'},
       {'name': 'Patricia Hardy', 'mail': 'phicks@hotmail.com',
        'residence': '962 Lindsey Light Apt. 133\nSouth Jenniferfurt, AR 30215'},
       {'name': 'Anne Perez', 'mail': 'steven41@hotmail.com',
        'residence': '2982 Kristin Orchard\nSouth Jessicaport, MN 20338'},
       {'name': 'Jerome Gross Jr.', 'mail': 'chamberserin@hotmail.com',
        'residence': '861 Allen Keys Apt. 665\nSouth Donnabury, WA 43110'},
       {'name': 'Crystal Palmer', 'mail': 'craigmiles@hotmail.com',
        'residence': '103 Santiago Mountain\nGibsonton, NH 20770'},
       {'name': 'James Patrick', 'mail': 'klucas@gmail.com',
        'residence': 'PSC 0300, Box 1060\nAPO AA 01295'},
       {'name': 'Russell Mills', 'mail': 'uhendricks@yahoo.com',
        'residence': '352 Mary Expressway Apt. 855\nLake Timothy, VT 09748'},
       {'name': 'Brian Coleman', 'mail': 'michael50@yahoo.com',
        'residence': '0799 Terri Crest Suite 614\nJefferychester, KY 17857'},
       {'name': 'Pamela Hill', 'mail': 'huntjulia@gmail.com',
        'residence': '5800 Richard Mountain Apt. 783\nLake Juanmouth, GA 75448'},
       {'name': 'Christopher Warner', 'mail': 'rangeldonald@hotmail.com',
        'residence': '6480 Wise Port\nLawrencetown, AK 86388'},
       {'name': 'Patrick Gonzalez', 'mail': 'mathewwillis@yahoo.com',
        'residence': '4442 Christopher Drive\nSouth Courtney, TX 31352'},
       {'name': 'Adam Rice', 'mail': 'hchandler@yahoo.com',
        'residence': '0307 Mora Road\nMaryfort, KS 94628'},
       {'name': 'Latoya Li', 'mail': 'christopher30@hotmail.com',
        'residence': '06477 John Village Suite 149\nSamanthaville, MI 06360'},
       {'name': 'William Montgomery', 'mail': 'josephmedina@hotmail.com',
        'residence': 'USNS Johnson\nFPO AE 33052'},
       {'name': 'Linda Jackson', 'mail': 'ghartman@hotmail.com',
        'residence': '454 Gregory Prairie\nHarveyside, FL 03208'},
       {'name': 'John Pacheco', 'mail': 'reedstephanie@yahoo.com',
        'residence': '330 Thomas Mount Suite 854\nSouth Colin, IL 94529'},
       {'name': 'Courtney Barnes', 'mail': 'randy61@gmail.com',
        'residence': '841 Gonzalez Falls\nWadechester, AL 42896'},
       {'name': 'Jessica Atkins', 'mail': 'dbradshaw@hotmail.com',
        'residence': '5532 Dixon Cliffs Suite 512\nBanksbury, TX 88897'},
       {'name': 'Ricardo Allen', 'mail': 'perryrachel@yahoo.com',
        'residence': '000 Weber Summit Suite 211\nSusanside, AZ 04145'},
       {'name': 'Kellie Holland', 'mail': 'psmith@gmail.com',
        'residence': 'Unit 8210 Box 8537\nDPO AE 10119'},
       {'name': 'John Martin', 'mail': 'russellannette@gmail.com',
        'residence': '6944 Lee Plains\nLake Laura, NH 91177'},
       {'name': 'Benjamin Johnston', 'mail': 'imorse@gmail.com',
        'residence': '546 Cody Oval Apt. 608\nNew Joanne, NE 24750'},
       {'name': 'Stephanie Lee', 'mail': 'kelsey02@hotmail.com',
        'residence': '8344 Elliott Forks Apt. 707\nNorth Alicia, DE 42231'},
       {'name': 'Christina Gilbert', 'mail': 'icarter@gmail.com',
        'residence': '289 Williams Harbors\nSouth William, ME 36470'},
       {'name': 'Jerry Adams', 'mail': 'zbrown@hotmail.com', 'residence': '347 Donald Island\nJulieview, KY 70621'}]


expected_ex3 = [{'name': 'Nicole Weber', 'mail': 'wilkinsjoshua@hotmail.com'},
       {'name': 'Amy Newton', 'mail': 'wbenson@yahoo.com'},
       {'name': 'Cheryl Rodriguez', 'mail': 'jimenezjennifer@hotmail.com'},
       {'name': 'Deborah Fuller', 'mail': 'troydavidson@yahoo.com'},
       {'name': 'Erica Berry', 'mail': 'gregory49@yahoo.com'},
       {'name': 'Christine Wilson', 'mail': 'psantiago@gmail.com'},
       {'name': 'Shari Hardy', 'mail': 'tsparks@hotmail.com'},
       {'name': 'Connie Lowery', 'mail': 'simsbrandon@yahoo.com'}]


expected_ex4 = [{'name': 'Kurt Wiggins', 'residence': 'GA', 'mail': 'mlittle@hotmail.com'},
       {'name': 'Steven Reed', 'residence': 'KS',
           'mail': 'jonathanortega@gmail.com'},
       {'name': 'Edwin Allen', 'residence': 'NV',
           'mail': 'rachelguzman@hotmail.com'},
       {'name': 'Jeffrey Murphy', 'residence': 'SD',
        'mail': 'samanthacook@hotmail.com'},
       {'name': 'Michael Mckee', 'residence': 'OH', 'mail': 'janet61@hotmail.com'},
       {'name': 'Joseph Johnson', 'residence': 'LA', 'mail': 'claudia66@gmail.com'},
       {'name': 'Isaac Foster', 'residence': 'ME', 'mail': 'ashleyboyle@yahoo.com'},
       {'name': 'Kevin Gilbert', 'residence': 'SD',
        'mail': 'jordanchristine@hotmail.com'},
       {'name': 'Ryan Howell', 'residence': 'NH', 'mail': 'uroberts@gmail.com'},
       {'name': 'Michael Hudson', 'residence': 'KS', 'mail': 'kristina11@yahoo.com'},
       {'name': 'Scott Lee', 'residence': 'WA', 'mail': 'dmoore@yahoo.com'},
       {'name': 'Christopher Yates', 'residence': 'AK',
        'mail': 'devinoneill@hotmail.com'},
       {'name': 'Jerome Gross Jr.', 'residence': 'WA',
        'mail': 'chamberserin@hotmail.com'},
       {'name': 'Christopher Warner', 'residence': 'AK',
        'mail': 'rangeldonald@hotmail.com'},
       {'name': 'Ryan Booth', 'residence': 'CA', 'mail': 'gilmoreandrew@hotmail.com'}]
